from fastapi import APIRouter, HTTPException, Request, Depends
from typing import Dict, Any
import pandas as pd
from datetime import datetime, timedelta, UTC

try:
    from slowapi import Limiter
    from slowapi.util import get_remote_address
except ModuleNotFoundError:  # pragma: no cover - optional dependency
    Limiter = None  # type: ignore
    get_remote_address = None  # type: ignore

from ...db import supabase as supabase_db
from ...core.config import LEGAL_DISCLAIMER
from ...utils.auth import verify_api_key
from ...core.logging import get_logger

logger = get_logger(__name__)

router = APIRouter()


class DummyLimiter:  # pragma: no cover - simple fallback
    def limit(self, *_args, **_kwargs):
        def decorator(func):
            return func

        return decorator


limiter = Limiter(key_func=get_remote_address) if Limiter and get_remote_address else DummyLimiter()
rate_limit = limiter.limit

@router.get("/signals")
@rate_limit("30/minute")
async def get_signals(request: Request, authenticated: bool = Depends(verify_api_key)):
    """
    Get current trading signals for all tracked symbols from the database.

    Signals are generated by the trading bot during market hours and stored in the database.
    This endpoint retrieves the latest signals (within the last 15 minutes) to avoid
    rate limit abuse on external market data APIs.
    """
    try:
        supabase = supabase_db.get_supabase_client()

        # Get latest signals from database (last 15 minutes to ensure freshness)
        fifteen_min_ago = (datetime.now(UTC) - timedelta(minutes=15)).isoformat()

        # Query signals table for recent signals
        response = supabase.table("signals") \
            .select("*") \
            .gte("created_at", fifteen_min_ago) \
            .order("created_at", desc=True) \
            .execute()

        logger.info(f"Retrieved {len(response.data) if response.data else 0} signals from database")

        # Group signals by symbol (keep only latest per symbol)
        signals_data = {}
        latest_timestamp = None

        if response.data:
            # Use a dict to track latest signal per symbol
            symbol_signals = {}
            for signal in response.data:
                symbol = signal["symbol"]
                signal_time = signal.get("created_at") or signal.get("timestamp")

                # Keep only the most recent signal for each symbol
                if symbol not in symbol_signals:
                    symbol_signals[symbol] = signal
                else:
                    existing_time = symbol_signals[symbol].get("created_at") or symbol_signals[symbol].get("timestamp")
                    if signal_time > existing_time:
                        symbol_signals[symbol] = signal

            # Build response for each symbol
            for symbol, signal in symbol_signals.items():
                # Create conditions object based on technical indicators
                conditions = {}
                signal_type = signal["signal_type"].upper()

                # SMA crossover condition
                if signal.get("sma_20") is not None and signal.get("sma_50") is not None:
                    sma_20 = float(signal["sma_20"])
                    sma_50 = float(signal["sma_50"])
                    if signal_type == "BUY":
                        conditions['sma_crossover'] = sma_20 > sma_50
                    elif signal_type == "SELL":
                        conditions['sma_crossover'] = sma_20 < sma_50

                # RSI filter condition
                if signal.get("rsi") is not None:
                    rsi = float(signal["rsi"])
                    if signal_type == "BUY":
                        conditions['rsi_filter'] = rsi < 70
                    elif signal_type == "SELL":
                        conditions['rsi_filter'] = rsi > 30

                signals_data[symbol] = {
                    "signal": signal_type,
                    "sma_20": float(signal["sma_20"]) if signal.get("sma_20") is not None else None,
                    "sma_50": float(signal["sma_50"]) if signal.get("sma_50") is not None else None,
                    "rsi": float(signal["rsi"]) if signal.get("rsi") is not None else None,
                    "current_price": float(signal["price"]),
                    "conditions": conditions,
                    "strength": float(signal["strength"])
                }

                # Track latest timestamp
                signal_time = signal.get("created_at") or signal.get("timestamp")
                if latest_timestamp is None or signal_time > latest_timestamp:
                    latest_timestamp = signal_time

        # If no signals found in database, return empty response (don't compute default AAPL)
        if not signals_data:
            logger.info("No recent signals found in database (bot may not have run yet)")

        return {
            "signals": signals_data,
            "timestamp": latest_timestamp or datetime.now(UTC).isoformat(),
            "data_delay_minutes": 15,  # As per PRD requirement
            "disclaimer": LEGAL_DISCLAIMER
        }
    except Exception as e:
        logger.error(f"Error retrieving signals: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e)) 
